use_frameworks!

def default_pods
  pod 'SwiftyUIEssentials', :path => '../'
end

target 'SwiftyUIEssentials_Example' do
  default_pods
end
target 'SwiftyUIEssentials_Tests' do
  default_pods
end
target 'SwiftyUIEssentials_UITests' do
  default_pods
end
