# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode10.2
xcode_sdk: iphonesimulator12.2
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install xcpretty
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail
- travis_retry xcodebuild -workspace Example/SwiftyUIEssentials.xcworkspace -scheme SwiftyUIEssentials-Example -destination "platform=iOS Simulator,name=iPhone 8" build-for-testing test | xcpretty
- pod lib lint